name: Deploy to VPS on push to main (Password Auth)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v2  # Updated version for password support
        with:
          host: 202.10.36.151
          username: root
          password: ${{ secrets.PASSWORD }}  # New secret for password
          port: 22
          script: |
            cd ../home/book-library/FE-Book-Finder
            git pull origin main