name: Update on Main Branch Push

on:
  push:
    branches:
      - main

jobs:
  update:
    name: SSH into VPS and Update
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: SSH into VPS and update files
      uses: appleboy/ssh-action@master
      with:
        host: 202.10.36.151
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /path/to/your/cloned/repository
          git pull origin main