name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t fe-book-finder .

    - name: Transfer Docker image to VPS
      uses: appleboy/scp-action@master
      with:
        host: 202.10.36.151
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "../home/book-library"
        port: 22
      
    - name: SSH into VPS and start Docker container
      uses: appleboy/ssh-action@master
      with:
        host: 202.10.36.151
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ../home/book-library
          docker run -d -p 8080:8080 fe-book-finder