name: Update on Main Branch Push

on:
  push:
    branches:
      - main

jobs:
  update:
    name: SSH into VPS and Update
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        private-key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA6flNqwaiU72f8gUwEv5f3fII7GmSGqtxzF2WvmNw3aHl//1L0EEx
VpqN2kg/JpOrgC70yZSdrmX6XR+cJA8QehTVt/s4ZJBzEshqaiGPSeo9+dtPbHpnLKXlMZ
n6bN5IX1lJRYx7MGIPLTErGjnjqNBnyjRH/sRJQB6uMf+mlyNaiq/Kwb9Cq43/wKz0pfjW
TEFfbUEbWjIhQI0xtUtFusV4LsFM75VS7VMCLnhE3iFuuz7Z6RWvgjeWUmefbE1o5fLE9E
RNB1W4ScwXBYB8h1DLDICgrmFFvQ9zkUpmyjSSz24QUSrpIB6xzam+5V5WxuEWRnQqHzJx
XBb8ONHAgXoboLl8TnsKymL8dapWJ1jmJ/EDJh0VcQ1KtorkU5eSJCjiXZJFQnbX7GKgsO
FxD4WPQW0xWrMRdGWUxZsSO0jjGIqsEVV4rHcy5P0BjY7F5EsuADa0Hf56exEa9lZLI/S0
juhNpx4D+4fV0manB6LpU8hM39jPAc5k1HIM54Ck+PEwXRIv1W5u0kSpfz0r0qY/U51MAl
oK++TpcXc8XT0bpfNRQ1LoKhPfLwN39P3tNxndiyzykfyl67wQWIC8w2+3zDWtqTgw583V
B8OtaRxL7jGyJ8nU4rdE0LW6fR2ZDedIqhdTSk3NbWTHk/iRDrvS5WJoLmBQY44/4R+X94
EAAAdQZbdmi2W3ZosAAAAHc3NoLXJzYQAAAgEA6flNqwaiU72f8gUwEv5f3fII7GmSGqtx
zF2WvmNw3aHl//1L0EExVpqN2kg/JpOrgC70yZSdrmX6XR+cJA8QehTVt/s4ZJBzEshqai
GPSeo9+dtPbHpnLKXlMZn6bN5IX1lJRYx7MGIPLTErGjnjqNBnyjRH/sRJQB6uMf+mlyNa
iq/Kwb9Cq43/wKz0pfjWTEFfbUEbWjIhQI0xtUtFusV4LsFM75VS7VMCLnhE3iFuuz7Z6R
WvgjeWUmefbE1o5fLE9ERNB1W4ScwXBYB8h1DLDICgrmFFvQ9zkUpmyjSSz24QUSrpIB6x
zam+5V5WxuEWRnQqHzJxXBb8ONHAgXoboLl8TnsKymL8dapWJ1jmJ/EDJh0VcQ1KtorkU5
eSJCjiXZJFQnbX7GKgsOFxD4WPQW0xWrMRdGWUxZsSO0jjGIqsEVV4rHcy5P0BjY7F5Esu
ADa0Hf56exEa9lZLI/S0juhNpx4D+4fV0manB6LpU8hM39jPAc5k1HIM54Ck+PEwXRIv1W
5u0kSpfz0r0qY/U51MAloK++TpcXc8XT0bpfNRQ1LoKhPfLwN39P3tNxndiyzykfyl67wQ
WIC8w2+3zDWtqTgw583VB8OtaRxL7jGyJ8nU4rdE0LW6fR2ZDedIqhdTSk3NbWTHk/iRDr
vS5WJoLmBQY44/4R+X94EAAAADAQABAAACAAkeXxFfdfvHLqYgifdGNFdH47gkWdOHQ1f1
0nZYwCErJPXH7z35DyKzGFHdsfRfb0t/c6ktjRhVv3RZ/dxb5/D8weLkkWs97qDYmxPIJg
z5P5wZbiwp+GkW4r/+98cUF1mmoa0/udywswBjDlfR0hZrX41+YctDPCBEcdaKAk9D9fc6
EwVfs7SlmUZEQgP77DeBmWX+fRc+pT7I90XRCVvWRAZSdfH6bbEeeeh0uykLFYU1AF94qb
lB+wOlfThGgLmW2hKJB5WAbj5rYVRPZcsM8jTqXcNzZWPmZ8MjAAQ5GKWpQk0028Fq4NQa
nabTzpRRWRcQLO9qqFywmqOI7TSA3tt9U+EW5WvbGUtW+/PCt+Nh6klCsjkcdTnxX0QR4r
CkAW9/63IrNUAZEmqCFKxVLFXRmTRVqyqS1dvQ0mwhzXiy5Lv7Mvmq3mrrHFBi2Coouiqp
AwFpCLZLRePf4hzuBnW/KkZ7dkiCgA4kCXBIK1tzk+sOBk62FwUmA0baOpT2fLKJKj3ZFn
O3tqrqxRzJ/Aq/QRPaUfTz4TKqZNls/E15EJ034ZSQk5VaXHN7YuRX8wrdVTCqEPCWqKA6
cGjo9cGLFD/dUukL/acB6JlyY4D7os5i/0tfa2Cu97akhe+k2DjgIJgGY6lopgZB9rxGuD
KQ0tUmTMUfMrZJD10hAAABAQDFjdNGHh5X2/hiszsax0ggUUX3Hl63OW8OE+qOqMeRKV69
qSiXO8vwV4hFmpjWyoVJIF1OBQDAp4swHXG5WoK29p+3NefXrBQK6iewSDj4GIQclDb1RJ
DrdjxI5SOhB/t0tAByFKucHXQnWsAs+ZgZ91EihGtdLSInoSGbC82Hr/q3syNyf7RVGfe8
qa11PtN5RhFOlWkQWUQb4Tk90webpIGfsdfU0WCQQb7DMCjCa4GwvaIlRCbBlEaga2QpJr
dcFvOYAvrecx7+iZOrEOf8dmJLlnYZiT3SRAoJ3MtdMEZzno00sR1gv+xloJPVFowOclL4
DpbHNUwHome7khM9AAABAQDy6Hwh1pQBs1dAWzCJhgGpydjzvJy3tn3U35ViCYtgVV5dlI
iPVC9cD+0JAtDwMjBBNqLEQ/n0UztCqb7vM3HWKFcZOCFCTzvk1kU0NlWJlZBgACZCGtTM
XUYFo6zJfyvEpjoRw7T6niD6pqmYxafWJEGzQocXAfqdel9+L93MzTHpAaQh4khyiYbujC
        public-key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDp+U2rBqJTvZ/yBTAS/l/d8gjsaZIaq3HMXZa+Y3DdoeX//UvQQTFWmo3aSD8mk6uALvTJlJ2uZfpdH5wkDxB6FNW3+zhkkHMSyGpqIY9J6j35209semcspeUxmfps3khfWUlFjHswYg8tMSsaOeOo0GfKNEf+xElAHq4x/6aXI1qKr8rBv0Krjf/ArPSl+NZMQV9tQRtaMiFAjTG1S0W6xXguwUzvlVLtUwIueETeIW67PtnpFa+CN5ZSZ59sTWjl8sT0RE0HVbhJzBcFgHyHUMsMgKCuYUW9D3ORSmbKNJLPbhBRKukgHrHNqb7lXlbG4RZGdCofMnFcFvw40cCBehuguXxOewrKYvx1qlYnWOYn8QMmHRVxDUq2iuRTl5IkKOJdkkVCdtfsYqCw4XEPhY9BbTFasxF0ZZTFmxI7SOMYiqwRVXisdzLk/QGNjsXkSy4ANrQd/np7ERr2Vksj9LSO6E2nHgP7h9XSZqcHoulTyEzf2M8BzmTUcgzngKT48TBdEi/Vbm7SRKl/PSvSpj9TnUwCWgr75OlxdzxdPRul81FDUugqE98vA3f0/e03Gd2LLPKR/KXrvBBYgLzDb7fMNa2pODDnzdUHw61pHEvuMbInydTit0TQtbp9HZkN50iqF1NKTc1tZMeT+JEOu9LlYmguYFBjjj/hH5f3gQ== rizkyrevanda@gmail.com
        
    - name: SSH into VPS and update files
      uses: appleboy/ssh-action@master
      with:
        host: 202.10.36.151
        username: root
        key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA6flNqwaiU72f8gUwEv5f3fII7GmSGqtxzF2WvmNw3aHl//1L0EEx
VpqN2kg/JpOrgC70yZSdrmX6XR+cJA8QehTVt/s4ZJBzEshqaiGPSeo9+dtPbHpnLKXlMZ
n6bN5IX1lJRYx7MGIPLTErGjnjqNBnyjRH/sRJQB6uMf+mlyNaiq/Kwb9Cq43/wKz0pfjW
TEFfbUEbWjIhQI0xtUtFusV4LsFM75VS7VMCLnhE3iFuuz7Z6RWvgjeWUmefbE1o5fLE9E
RNB1W4ScwXBYB8h1DLDICgrmFFvQ9zkUpmyjSSz24QUSrpIB6xzam+5V5WxuEWRnQqHzJx
XBb8ONHAgXoboLl8TnsKymL8dapWJ1jmJ/EDJh0VcQ1KtorkU5eSJCjiXZJFQnbX7GKgsO
FxD4WPQW0xWrMRdGWUxZsSO0jjGIqsEVV4rHcy5P0BjY7F5EsuADa0Hf56exEa9lZLI/S0
juhNpx4D+4fV0manB6LpU8hM39jPAc5k1HIM54Ck+PEwXRIv1W5u0kSpfz0r0qY/U51MAl
oK++TpcXc8XT0bpfNRQ1LoKhPfLwN39P3tNxndiyzykfyl67wQWIC8w2+3zDWtqTgw583V
B8OtaRxL7jGyJ8nU4rdE0LW6fR2ZDedIqhdTSk3NbWTHk/iRDrvS5WJoLmBQY44/4R+X94
EAAAdQZbdmi2W3ZosAAAAHc3NoLXJzYQAAAgEA6flNqwaiU72f8gUwEv5f3fII7GmSGqtx
zF2WvmNw3aHl//1L0EExVpqN2kg/JpOrgC70yZSdrmX6XR+cJA8QehTVt/s4ZJBzEshqai
GPSeo9+dtPbHpnLKXlMZn6bN5IX1lJRYx7MGIPLTErGjnjqNBnyjRH/sRJQB6uMf+mlyNa
iq/Kwb9Cq43/wKz0pfjWTEFfbUEbWjIhQI0xtUtFusV4LsFM75VS7VMCLnhE3iFuuz7Z6R
WvgjeWUmefbE1o5fLE9ERNB1W4ScwXBYB8h1DLDICgrmFFvQ9zkUpmyjSSz24QUSrpIB6x
zam+5V5WxuEWRnQqHzJxXBb8ONHAgXoboLl8TnsKymL8dapWJ1jmJ/EDJh0VcQ1KtorkU5
eSJCjiXZJFQnbX7GKgsOFxD4WPQW0xWrMRdGWUxZsSO0jjGIqsEVV4rHcy5P0BjY7F5Esu
ADa0Hf56exEa9lZLI/S0juhNpx4D+4fV0manB6LpU8hM39jPAc5k1HIM54Ck+PEwXRIv1W
5u0kSpfz0r0qY/U51MAloK++TpcXc8XT0bpfNRQ1LoKhPfLwN39P3tNxndiyzykfyl67wQ
WIC8w2+3zDWtqTgw583VB8OtaRxL7jGyJ8nU4rdE0LW6fR2ZDedIqhdTSk3NbWTHk/iRDr
vS5WJoLmBQY44/4R+X94EAAAADAQABAAACAAkeXxFfdfvHLqYgifdGNFdH47gkWdOHQ1f1
0nZYwCErJPXH7z35DyKzGFHdsfRfb0t/c6ktjRhVv3RZ/dxb5/D8weLkkWs97qDYmxPIJg
z5P5wZbiwp+GkW4r/+98cUF1mmoa0/udywswBjDlfR0hZrX41+YctDPCBEcdaKAk9D9fc6
EwVfs7SlmUZEQgP77DeBmWX+fRc+pT7I90XRCVvWRAZSdfH6bbEeeeh0uykLFYU1AF94qb
lB+wOlfThGgLmW2hKJB5WAbj5rYVRPZcsM8jTqXcNzZWPmZ8MjAAQ5GKWpQk0028Fq4NQa
nabTzpRRWRcQLO9qqFywmqOI7TSA3tt9U+EW5WvbGUtW+/PCt+Nh6klCsjkcdTnxX0QR4r
CkAW9/63IrNUAZEmqCFKxVLFXRmTRVqyqS1dvQ0mwhzXiy5Lv7Mvmq3mrrHFBi2Coouiqp
AwFpCLZLRePf4hzuBnW/KkZ7dkiCgA4kCXBIK1tzk+sOBk62FwUmA0baOpT2fLKJKj3ZFn
O3tqrqxRzJ/Aq/QRPaUfTz4TKqZNls/E15EJ034ZSQk5VaXHN7YuRX8wrdVTCqEPCWqKA6
cGjo9cGLFD/dUukL/acB6JlyY4D7os5i/0tfa2Cu97akhe+k2DjgIJgGY6lopgZB9rxGuD
KQ0tUmTMUfMrZJD10hAAABAQDFjdNGHh5X2/hiszsax0ggUUX3Hl63OW8OE+qOqMeRKV69
qSiXO8vwV4hFmpjWyoVJIF1OBQDAp4swHXG5WoK29p+3NefXrBQK6iewSDj4GIQclDb1RJ
DrdjxI5SOhB/t0tAByFKucHXQnWsAs+ZgZ91EihGtdLSInoSGbC82Hr/q3syNyf7RVGfe8
qa11PtN5RhFOlWkQWUQb4Tk90webpIGfsdfU0WCQQb7DMCjCa4GwvaIlRCbBlEaga2QpJr
dcFvOYAvrecx7+iZOrEOf8dmJLlnYZiT3SRAoJ3MtdMEZzno00sR1gv+xloJPVFowOclL4
DpbHNUwHome7khM9AAABAQDy6Hwh1pQBs1dAWzCJhgGpydjzvJy3tn3U35ViCYtgVV5dlI
iPVC9cD+0JAtDwMjBBNqLEQ/n0UztCqb7vM3HWKFcZOCFCTzvk1kU0NlWJlZBgACZCGtTM
XUYFo6zJfyvEpjoRw7T6niD6pqmYxafWJEGzQocXAfqdel9+L93MzTHpAaQh4khyiYbujC
        script: |
          cd /path/to/your/cloned/repository
          git pull origin main